import { useMemo } from 'react';
import {
  Alignment,
  Autoformat,
  AutoImage,
  Autosave,
  Base64UploadAdapter,
  Bold,
  Essentials,
  FontColor,
  FontFamily,
  FontSize,
  GeneralHtmlSupport,
  ImageBlock,
  ImageInline,
  ImageInsert,
  ImageInsertViaUrl,
  ImageResize,
  ImageStyle,
  ImageTextAlternative,
  ImageToolbar,
  ImageUpload,
  Italic,
  List,
  ListProperties,
  PageBreak,
  Paragraph,
  PasteFromOffice,
  Table,
  TableCellProperties,
  TableColumnResize,
  TableProperties,
  TableToolbar,
  TextTransformation,
  TodoList,
  Underline,
  Clipboard,
  Link,
} from 'ckeditor5';

import translations from 'ckeditor5/translations/ko.js';
import defaultContent from '../constants/defaultContent.js';

export const useEditorConfig = isLayoutReady => {
  const LICENSE_KEY = 'GPL';

  return useMemo(() => {
    if (!isLayoutReady) return {};

    return {
      editorConfig: {
        toolbar: {
          items: [
            'fontSize',
            'fontFamily',
            'fontColor',
            '|',
            'bold',
            'italic',
            'underline',
            '|',
            'pageBreak',
            'insertTable',
            '|',
            'alignment',
            '|',
            'bulletedList',
            'numberedList',
            'todoList',
          ],
          shouldNotGroupWhenFull: false,
        },
        plugins: [
          Alignment,
          Autoformat,
          AutoImage,
          Autosave,
          Base64UploadAdapter,
          Bold,
          Clipboard,
          Essentials,
          FontColor,
          FontFamily,
          FontSize,
          GeneralHtmlSupport,
          ImageBlock,
          ImageInline,
          ImageInsert,
          ImageInsertViaUrl,
          ImageResize,
          ImageStyle,
          ImageTextAlternative,
          ImageToolbar,
          ImageUpload,
          Italic,
          List,
          ListProperties,
          Link,
          PageBreak,
          Paragraph,
          PasteFromOffice,
          Table,
          TableCellProperties,
          TableColumnResize,
          TableProperties,
          TableToolbar,
          TextTransformation,
          TodoList,
          Underline,
        ],
        fontFamily: {
          supportAllValues: true,
        },
        fontSize: {
          options: [
            { title: '8pt', model: '10.6667px' },
            { title: '9pt', model: '12px' },
            { title: '10pt (기본)', model: '13.3333px' },
            { title: '11pt', model: '14.6667px' },
            { title: '12pt', model: '16px' },
            { title: '14pt', model: '18.6667px' },
            { title: '16pt', model: '21.3333px' },
            { title: '18pt', model: '24px' },
            { title: '20pt', model: '26.6667px' },
            { title: '22pt', model: '29.3333px' },
            { title: '24pt', model: '32px' },
            { title: '26pt', model: '34.6667px' },
            { title: '28pt', model: '37.3333px' },
            { title: '36pt', model: '48px' },
            { title: '48pt', model: '64px' },
            { title: '72pt', model: '96px' },
          ],
          supportAllValues: true,
          default: '13.3333px',
        },
        htmlSupport: {
          allow: [
            {
              name: /^.*$/,
              styles: true,
              attributes: true,
              classes: true,
            },
            {
              name: 'a',
              attributes: ['href', 'target', 'rel'],
              classes: true,
              styles: true,
            },
          ],
        },
        image: {
          toolbar: [
            'imageTextAlternative',
            '|',
            'imageStyle:inline',
            'imageStyle:wrapText',
            'imageStyle:breakText',
            '|',
            'resizeImage',
          ],
        },
        initialData: defaultContent,
        language: 'ko',
        licenseKey: LICENSE_KEY,
        list: {
          properties: {
            styles: true,
            startIndex: true,
            reversed: true,
          },
        },
        placeholder: 'Type or paste your content here!',
        table: {
          contentToolbar: [
            'tableColumn',
            'tableRow',
            'mergeTableCells',
            'tableProperties',
            'tableCellProperties',
          ],
        },
        translations: [translations],
        contentCss: ['body { font-size: 10pt; }'],
      },
    };
  }, [isLayoutReady]);
};
